[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

# Use the forge-std that comes via OpenZeppelin (no top-level forge-std needed)
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/",
]

[rpc_endpoints]
whitechain = "${WHITECHAIN_RPC_URL}"
